#!/usr/bin/env bash

NGRINDER_CONTROLLER_IP=${NGRINDER_CONTROLLER_IP:-ngrinder-controller}
echo "NGRINDER_CONTROLLER_IP =" $NGRINDER_CONTROLLER_IP

NGRINDER_CONTROLLER_PORT=${NGRINDER_CONTROLLER_PORT:-16001}
echo "NGRINDER_CONTROLLER_PORT =" $NGRINDER_CONTROLLER_PORT

NGRINDER_MONITOR_BINDING_IP=${NGRINDER_MONITOR_BINDING_IP:-localhost}
echo "NGRINDER_MONITOR_BINDING_IP =" $NGRINDER_MONITOR_BINDING_IP

NGRINDER_MONITOR_BINDING_PORT=${NGRINDER_MONITOR_BINDING_PORT:-13243}
echo "NGRINDER_MONITOR_BINDING_PORT =" $NGRINDER_MONITOR_BINDING_PORT

# # Altering the configuration files

echo "agent.controller_host=$NGRINDER_CONTROLLER_IP" >> $NGRINDER_AGENT_HOME/__agent.conf
echo "agent.controller_port=$NGRINDER_CONTROLLER_PORT" >> $NGRINDER_AGENT_HOME/__agent.conf

# sed s/monitor.binding_ip=/$NGRINDER_MONITOR_BINDING_IP/ $NGRINDER_MONITOR_HOME/__agent.conf
# sed s/monitor.binding_port=/$NGRINDER_MONITOR_BINDING_PORT/ $NGRINDER_MONITOR_HOME/__agent.conf

echo "monitor.binding_ip=$NGRINDER_MONITOR_BINDING_IP" >> $NGRINDER_MONITOR_HOME/__agent.conf
echo "monitor.binding_port=$NGRINDER_MONITOR_BINDING_PORT" >> $NGRINDER_MONITOR_HOME/__agent.conf

# Run the NGRINDER agent
$NGRINDER_AGENT_HOME/run_agent.sh -o &

# Run the NGRINDER monitor
$NGRINDER_MONITOR_HOME/run_monitor.sh -o &